konten = {      1: "Kasse",
                2: "Bankkonto" }

eurkonten = { 111: "Betriebseinnahmen nach &para;19 Abs. 1 UStG.",
              141: "Vom Finanzamt erstattete/verrechnete Umsatzsteuer",
              102: "Ver&auml;sserung oder Entnahme von Anlageverm&ouml;gen",
              106: "Private Kfz-Nutzung",
              108: "Sonstige Sach-, Nutzungs- und Leistungsentnahmen",
              100: "Waren, Roh- und Hilfsstoffe",
              110: "Bezogene Fremdleistungen",
              120: "Personalausgaben",
              136: "AfA auf unbewegliche Wirtschaftsg&uuml;ter",
              131: "AfA auf immaterielle Wirtschaftsg&uuml;ter",
              130: "AfA auf bewegliche Wirtschaftsg&uuml;ter",
              150: "Miete/Pacht f&uuml;r Gesch&auml;ftsr&auml;me",
              152: "Aufwendungen f&uuml;r doppelte Haushaltsf&uuml;hrung",
              151: "Sonstige Aufwendungen f&uuml;r betrieblich genutzte Grundst&uuml;cke",
              280: "Aufwendungen f&uuml;r Telekommunikation",
              221: "&Uuml;bernachtungs- und Reisekosten",
              281: "Fortbildungskosten (ohne Reisekosten)",
              194: "Kosten f&uuml;r Rechts- und Steuerberatung, Buchf&uuml;hrung",
              222: "Miete/Leasing f&uuml;r bewegliche Wirtschaftsg&uuml;ter (ohne Kfz)",
              223: "Beitr&auml;ge, Geb&uuml;hren, Abgaben und Versicherungen",
              224: "Werbekosten",
              232: "Schuldzinsen zur Finanzierung von Anschaffungs- und Herstellungskosten",
              234: "&Uuml;brige Schuldzinsen",
              185: "Gezahlte Vorsteuerbetr&auml;ge",
              186: "An das Finanzamt gezahlte/verrechnete USt.",
              183: "&Uuml;brige unbeschr&auml;nkt abziehbare Betriebsausgaben",
              164: "Geschenke",
              165: "Bewirtungsaufwendungen",
              162: "Aufwendungen f&uuml;r ein h&auml;sliches Arbeitszimmer",
              168: "Sonstige beschr&auml;nkt abziehbare Betriebsausgaben",
              217: "Gewerbesteuer",
              144: "Leasingkosten Kfz",
              145: "Steuern, Versicherungen und Maut",
              146: "Sonstige tats&auml;chliche Fahrtkosten",
              147: "Fahrtkosten f&uuml;r nicht zum Betriebsverm&ouml;gen geh&ouml;rende Fahrzeuge",
              142: "Kfz-Kosten f&uuml;r Wege zwischen Wohnung und erster Betriebsst&auml;tte",
              176: "Mindestens abziehbare Kfz-Kosten f&uuml;r Wege zwischen Wohnung und erster Betriebsst&auml;tte"

         }
