def get_eurkonten():

    eurkonten = { 111: "Betriebseinnahmen nach Paragraf 19 Abs. 1 UStG.",
                  141: "Vom Finanzamt erstattete/verrechnete Umsatzsteuer",
                  102: "Veraeusserung oder Entnahme von Anlagevermoegen",
                  106: "Private Kfz-Nutzung",
                  108: "Sonstige Sach-, Nutzungs- und Leistungsentnahmen",
                  100: "Waren, Roh- und Hilfsstoffe",
                  110: "Bezogene Fremdleistungen",
                  120: "Personalausgaben",
                  136: "AfA auf unbewegliche Wirtschaftsgueter",
                  131: "AfA auf immaterielle Wirtschaftsgueter",
                  130: "AfA auf bewegliche Wirtschaftsgueter",
                  150: "Miete/Pacht fuer Geschaeftsraeume",
                  152: "Aufwendungen fuer doppelte Haushaltsfuehrung",
                  151: "Sonstige Aufwendungen fuer betrieblich genutzte Grundstuecke",
                  280: "Aufwendungen fuer Telekommunikation",
                  221: "Uebernachtungs- und Reisekosten",
                  281: "Fortbildungskosten (ohne Reisekosten)",
                  194: "Kosten fuer Rechts- und Steuerberatung, Buchfuehrung",
                  222: "Miete/Leasing fuer bewegliche Wirtschaftsgueter (ohne Kfz)",
                  223: "Beitraege, Gebuehren, Abgaben und Versicherungen",
                  224: "Werbekosten",
                  232: "Schuldzinsen zur Finanzierung von Anschaffungs- und Herstellungskosten",
                  234: "Uebrige Schuldzinsen",
                  185: "Gezahlte Vorsteuerbetraege",
                  186: "An das Finanzamt gezahlte/verrechnete USt.",
                  183: "uebrige unbeschraenkt abziehbare Betriebsausgaben",
                  164: "Geschenke",
                  165: "Bewirtungsaufwendungen",
                  162: "Aufwendungen fuer ein haeusliches Arbeitszimmer",
                  168: "Sonstige beschraenkt abziehbare Betriebsausgaben",
                  217: "Gewerbesteuer",
                  144: "Leasingkosten Kfz",
                  145: "Steuern, Versicherungen und Maut",
                  146: "Sonstige tatsaechliche Fahrtkosten",
                  147: "Fahrtkosten fuer nicht zum Betriebsvermoegen gehoerende Fahrzeuge",
                  142: "Kfz-Kosten fuer Wege zwischen Wohnung und erster Betriebsstaette",
                  176: "Mindestens abziehbare Kfz-Kosten fuer Wege zwischen Wohnung und erster Betriebsstaette"

             }

    return eurkonten
